# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CalculTEOM
                                 A QGIS plugin
 Calcul de la TEOM à partir des données des fichiers fonciers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-11-25
        copyright            : (C) 2022 by Romain PELLICIER
        email                : r.pellicier@inddigo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Romain PELLICIER'
__date__ = '2022-11-25'
__copyright__ = '(C) 2022 by Romain PELLICIER'

# -*- coding: utf-8 -*-
import os
from datetime import datetime

from qgis.PyQt.QtCore import QCoreApplication

from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterProviderConnection,
    QgsProcessingParameterDatabaseSchema,
    QgsProcessingParameterFileDestination,
    QgsProviderRegistry
)

from .sql_loader import load_sql_file, execute_sql_list
from .excel_export import export_to_excel


class CalculTEOMAlgorithm(QgsProcessingAlgorithm):

    CONNEXION = "CONNEXION"
    SCHEMA = "SCHEMA"
    OUTPUT = "OUTPUT"

    # ---------------------------------------------------------------
    # INIT PARAMS
    # ---------------------------------------------------------------
    def initAlgorithm(self, config=None):

        # 1) Sélection de la connexion PostgreSQL native QGIS
        self.addParameter(
            QgsProcessingParameterProviderConnection(
                self.CONNEXION,
                "Connexion PostgreSQL",
                "postgres"
            )
        )

        # 2) Sélection du schéma dépendant de la connexion
        self.addParameter(
            QgsProcessingParameterDatabaseSchema(
                self.SCHEMA,
                "Schéma TEOM",
                self.CONNEXION
            )
        )

        # 3) Fichier de sortie XLSX
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                "Fichier Excel de sortie",
                "*.xlsx"
            )
        )

    # ---------------------------------------------------------------
    # PROCESS
    # ---------------------------------------------------------------
    def processAlgorithm(self, parameters, context, feedback):

        # -----------------------------
        # Connexion PostgreSQL
        # -----------------------------
        conn_name = self.parameterAsConnectionName(parameters, self.CONNEXION, context)
        md = QgsProviderRegistry.instance().providerMetadata("postgres")
        conn = md.findConnection(conn_name)
        if not conn:
            raise QgsProcessingException("Connexion PostgreSQL invalide.")
        
        # Vérification que la connexion pointe vers la base 'applicatifs'
        try:
            # Connexion DB "réelle"
            provider = QgsProviderRegistry.instance().providerMetadata("postgres")
            conn = provider.createConnection(conn_name)
            db_name = conn.executeSql("select current_database()")[0][0]

        except Exception as e:
            raise QgsProcessingException(f"Impossible de déterminer le nom de la base : {e}")

        # Test final
        if db_name != "applicatifs":
            raise QgsProcessingException(
                f"La connexion sélectionnée pointe vers la base <b>{db_name}</b> "
                f"au lieu de <b>applicatifs</b>.<br>"
                f"Veuillez sélectionner la connexion correcte."
            )

        # Schéma métier
        schema = self.parameterAsString(parameters, self.SCHEMA, context)
        if not schema:
            raise QgsProcessingException("Aucun schéma choisi.")

        output_file = self.parameterAsFileOutput(parameters, self.OUTPUT, context)

        feedback.pushInfo(f"Connexion : {conn_name}")
        feedback.pushInfo(f"Connexion PostgreSQL valide : base = {db_name}")
        feedback.pushInfo(f"Schéma TEOM source : {schema}")
        feedback.pushInfo("Chargement des fichiers SQL…")

        try:
            # -------------------------
            # Charger SQL local
            # -------------------------
            basepath = os.path.dirname(os.path.abspath(__file__))
            sql_folder = os.path.join(basepath, "queries")

            prep_sql = load_sql_file(os.path.join(sql_folder, "teom_preparation.sql"))
            type_sql = load_sql_file(os.path.join(sql_folder, "teom_type_locaux.sql"))

            all_sql = prep_sql + type_sql

            # -------------------------
            # Exécution SQL
            # (TEMP TABLES créées automatiquement dans pg_temp)
            # -------------------------
            results_base, results_locaux = execute_sql_list(
                conn,
                all_sql,
                schema,
                feedback
            )

            # -------------------------
            # Extraction pour Excel
            # -------------------------
            feedback.pushInfo("Extraction SQL pour Excel…")

            # sécurité
            if results_base is None:
                raise QgsProcessingException("La requête finale request7 n’a pas produit de résultat.")

            if results_locaux is None:
                raise QgsProcessingException("La requête finale type_locaux n’a pas produit de résultat.")

            # -------------------------
            # Titres Excel
            # -------------------------
            headings_base = (
                "Code insee", "EPCI", "Commune", "Invariant", "Parcelle", "Préfixe",
                "Section", "No plan", "Batiment", "Entrée", "Niveau", "Porte",
                "Code voie MAJIC", "Code voie rivoli", "Numéro de voirie",
                "Indice de répétition", "Nature", "Nom rue", "Compte communal",
                "Type de local", "Nature du Local", "Code d'occupation",
                "Local appartenant à hlm ou sem", "Exonération TEOM", "Zone TEOM",
                "Réduction TEOM", "Numéro de PEV", "Affectation PEV",
                "Code occupation à la TH ou à la TP", "Top construction nouvelle",
                "Top local passible de la TEOM", "Base TEOM", "Base TEOM écrêtée",
                "Montant TIEOM", "Taux TEOM", "MtTEOMssfg", "MtTEOMfg",
                "Nature de la dépendance", "Code du droit réel",
                "Indicateur du destinataire de l’avis d’imposition",
                "Nature personne", "Groupe personne", "Forme juridique abrégée",
                "Code NAF", "Section NAF", "Dénomination du propriétaire",
                "Adresse 1", "Adresse 2", "Adresse 3", "Adresse 4",
                "Numéro de voirie", "Code voie MAJIC", "Code voie rivoli",
                "Indice de répétition", "Code postal", "Nom d'usage", "Prénom",
                "Numéro SIREN", "Forme juridique", "Nombre d'étages",
                "Année de construction", "Présence du gaz", "Présence d’électricité",
                "Présence d’eau", "Nombre de pièce", "Superficie des pièces",
                "Matériaux des gros murs", "Matériaux des toitures",
                "État d’entretien"
            )

            headings_locaux = (
                "Commune",
                "Nombre de locaux",
                "Base TEOM",
                "Montant TEOM",

                "Nombre de locaux maison",
                "Base TEOM Maison",
                "Montant TEOM Maison",

                "Nombre de locaux Appartement",
                "Base TEOM Appartement",
                "Montant TEOM Appartement",

                "Nombre de locaux Dépendances",
                "Base TEOM Dépendances",
                "Montant TEOM Dépendances",

                "Nombre de locaux Commerciaux et Industriels",
                "Base TEOM Locaux Commerciaux et Industriels",
                "Montant TEOM Locaux Commerciaux et Industriels"
            )

            # -------------------------
            # Export Excel
            # -------------------------
            export_to_excel(
                results_base,
                headings_base,
                results_locaux,
                headings_locaux,
                output_file,
                feedback
            )

            return {self.OUTPUT: output_file}

        except Exception as e:
            feedback.reportError(f"ERREUR : {e}")
            raise QgsProcessingException(str(e))


    # ---------------------------------------------------------------
    # METADATA
    # ---------------------------------------------------------------
    def name(self):
        return "calcul_teom"

    def displayName(self):
        return "Export TEOM vers Excel"

    def group(self):
        return "TEOM"

    def groupId(self):
        return "teom"

    def tr(self, s):
        return QCoreApplication.translate("Processing", s)

    def createInstance(self):
        return CalculTEOMAlgorithm()

    def shortHelpString(self):
        return self.tr("""
        <p>Calcule la base TEOM complète via des tables temporaires PostgreSQL
        puis exporte les résultats vers un fichier Excel (.xlsx).</p>
        <h3>Paramètres</h3>
        <ul>
          <li><b>Connexion PostgreSQL</b> : Se connecter à la base <b>"applicatifs" obligatoirement </b></li>
                       
          <li><b>Schéma</b> : schéma contenant les tables TEOM, il peut être différent de "teom"</li>
          <li><b>Fichier Excel de sortie</b> : chemin du fichier Excel
          (.xlsx) à générer.</li>        
        
        <h3>Attention</h3>
                 <p>Les montants de TEOM sont claculés à partir d'un taux générique (0.1224), mais ce taux est en principe unique à chaque commune
                     puis multiplier par une autre taxe fixée par l'état : 1.08</p>       

        """)
